version: '3'
services:
  redis:
    hostname: rejson
    image: redislabs/rejson:latest
  web:
    container_name: gold_coin_web
    build:
     context: ./web
     dockerfile: Dockerfile-web
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
  scrapers:
    container_name: gold_coin_scrapers
    build: 
     context: ./scrapers
     dockerfile: Dockerfile