version: '3'
services:
  redis:
    image: redis
  web:
    build:
     context: .
     dockerfile: ./web/Dockerfile-web
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
  scrapers:
    build: 
     context: .
     dockerfile: ./scrapers/Dockerfile