apiVersion: v1
kind: Service
metadata:
  name: asset-mint-service
spec:
  selector:
    app: asset-mint
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-mint
spec:
  selector:
    matchLabels:
      app: asset-mint
  replicas: 4
  template:
    metadata:
      labels:
        app: asset-mint
    spec:
      containers:
      - name: asset-mint
        image: asset-mint:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000